{% set name = "btllib" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcgsc/btllib/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 51dd3d0e87222cc00032484c863be1f7cda42f006cdb60b209602a831e0fee32

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - samtools
    - pigz
    - gzip # alternative to pigz
    - tar
    - bzip2
    - xz
    - lrzip
    - zip
    - wget

about:
  home: https://github.com/bcgsc/btllib
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Bioinformatics common code library in C++ with Python wrappers, from Bioinformatics Technology Lab'
  