{% set name = "btllib" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcgsc/btllib/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: e300b6afc1ed10f3f4443f54753238cd5bc3133c686a5802ccb9e27baaf969b9

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - cmake
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - samtools
    - pigz
    - gzip # alternative to pigz
    - tar
    - bzip2
    - xz
    - lrzip
    - zip
    - wget

test:
  bin/indexlr --help

about:
  home: https://github.com/bcgsc/btllib
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Bioinformatics common code library in C++ with Python wrappers, from Bioinformatics Technology Lab'
