{% set name = "btllib" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bcgsc/btllib/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: e66e37ecbdb08c9f68d1db2bab2ff79178175a5b9c2eea28650c11a8cf6a4fe8 

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - gcc >=6.0.0
    - cmake
    - meson
    - ninja
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - pigz
    - gzip
    - bzip2
    - zlib
  run:
    - python
    - pigz
    - gzip
    - bzip2
    - zlib
    - make
    - samtools

about:
  home: https://github.com/bcgsc/btllib
  license: GPL-3.0
  license_file: LICENSE
  summary: 'Bioinformatics common code library in C++ with Python wrappers, from Bioinformatics Technology Lab'

  extra:
  container:
    # openmpi needs ssh/rsh
    extended-base: true