{% set name = "physlr" %}
{% set version = "1.0.2" %}
 
package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/bcgsc/{{ name|lower }}/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: bb53f14b31caa05b0f2eb5df64cebf4d27bb07a757fb73ffc788d5d8c9b71222

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - make
  host:
    - Python >=3.6.0
    - pip
    - boost-cpp
  run:
    - Python >=3.6.0
    - ntCard
    - ntHits
    - networkx
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - make
    - pigz
    
test:
  commands:
    - physlr version #| grep -q "{{ version }}"
    # - physlr help | grep -q "physlr physical-map"
    # - physlr help | grep -q "physlr scaffold"
    # - physlr test

about:
  home: https://github.com/bcgsc/physlr
  license: GPL3
  license_file: LICENSE
  summary: Physlr; Next-generation physical maps using linked reads
  dev_url: https://github.com/bcgsc/physlr
  doc_url: https://github.com/bcgsc/physlr#readme
